config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :entries
  # get 'pages/home'
  root "pages#home"
  devise_for :users
  get "journal", to: "pages#journal"
  get "thoughts", to: "pages#thoughts"
  get "faqs", to: "pages#faqs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  validates_presence_of :entrylog, :situation, :autothoughtDesc, :autothoughtExp, :emotionsDesc, :emotionsRate, :adaptiveResp, :outcomes
  # validates :situation, presence: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /records or /records.json
  def index
    #@records = Record.all
    @title = "All your thought records | journalite"
    @records = Record.where user_id: current_user.id
    @records = Record.order("created_at DESC").page(params[:page]).per(4)
  end

  # GET /records/1 or /records/1.json
  def show
    if @record.user_id != current_user.id
      redirect_to record_url
      return
    end
  end

  # GET /records/new
  def new
    @record = Record.new
    @record.user_id = current_user.id
  end

  # GET /records/1/edit
  def edit
    if @record.user_id != current_user.id
      redirect_to record_url
      return
    end
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)
    if @record.user_id != current_user.id
      redirect_to record_url
      return
    end
    respond_to do |format|
      if @record.save
        format.html { redirect_to record_url(@record), notice: "Your thought record was successfully created." }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    if @record.user_id != current_user.id
      redirect_to record_url
      return
    end
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: "Your thought record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    if @record.user_id != current_user.id
      redirect_to record_url
      return
    end
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url, notice: "Your thought record was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(:entrylog, :situation, :autothoughtDesc, :autothoughtExp, :emotionsDesc, :emotionsRate, :adaptiveResp, :outcomes, :user_id)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <section class="error">
      <h2>Uh oh!</h2>
      <p><%= pluralize(record.errors.count, "error") %> prevented your thought record from being created.</p>
      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </section>
  <% end %>
  <section>
    <%= form.label :entrylog, "Date and time", style: "display: block" %>
    <%= form.datetime_field :entrylog %>
  </section>
  <section>
    <%= form.label :situation, "Situation", style: "display: block" %>
    <p class="guide">What external or internal event is associated with the unpleasant emotion? Describe the unhelpful behaviour in which you engaged.</p>
    <%= form.text_area :situation, class: "page shorten" %>
  </section>
  <section>
    <%= form.label :autothoughtDesc, "Describe your automatic thoughts", style: "display: block" %>
    <p class="guide">What thoughts or images or both went through your mind before, during or after the event or unhelpful behaviour?</p>
    <%= form.text_area :autothoughtDesc, class: "page shorten" %>
  </section>
  <section>
    <%= form.label :autothoughtExp, "Explain your automatic thoughts", style: "display: block" %>
    <p class="guide">How much did you believe each thought or image?</p>
    <%= form.text_area :autothoughtExp, class: "page shorten" %>
  </section>
  <section>
    <%= form.label :emotionsDesc, "Describe your emotions", style: "display: block" %>
    <p class="guide">What emotions&mdash;sad, anxious, angry et cetera&mdash;did you feel before, during or after the event or unhelpful behaviour?</p>
    <%= form.text_area :emotionsDesc, class: "page shorten" %>
  </section>
  <section>
    <%= form.label :emotionsRate, "Rate your emotions", style: "display: block" %>
    <p class="guide">How intense was each emotion? Rate from 0 to 100%.</p>
    <%= form.text_area :emotionsRate, class: "page shorten" %>
  </section>
  <section>
    <%= form.label :adaptiveResp, "Adaptive responses (optional)", style: "display: block" %>
    <p class="guide">What cognitive distortions did you make? Use the sample questions to compose a response to each automatic thought. Indicate how much you believe each response.</p>
    <%= form.text_area :adaptiveResp, class: "page shorten" %>
  </section>
  <section>
    <%= form.label :outcomes, "Outcomes", style: "display: block" %>
    <p class="guide">How much do you now believe each automatic thought? List each emotion that you feel now? How intense is each emotion? Rate between 0 to 100%. What would be good to do?</p>
    <%= form.text_area :outcomes, class: "page shorten" %>
  </section>
  <section>
    <%= form.hidden_field :user_id %>
  </section>
  <section>
    <%= form.submit "Add record", :class => "btn j-btn new d-inline-block" %>
  </section>
<% end %>

app/views/records/_record.html.erb
<div id="<%= dom_id record %>">
  <h2 id="ent-heading">Record #<%= record.id %></h2>
  <p>
    <span class="t_rec d-inline-block"><strong>Date and time</strong></span><br>
    <%= record.entrylog %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Situation</strong></span><br>
    <%= record.situation %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Description of automatic thoughts</strong></span><br>
    <%= record.autothoughtDesc %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Explanation of automatic thoughts</strong></span><br>
    <%= record.autothoughtExp %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Description of emotions</strong></span><br>
    <%= record.emotionsDesc %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Rate of emotions</strong></span><br>
    <%= record.emotionsRate %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Adaptive responses</strong></span><br>
    <%= record.adaptiveResp %>
  </p>
  <p>
    <span class="t_rec d-inline-block"><strong>Outcomes</strong></span><br>
    <%= record.outcomes %>
  </p>
</div>

app/views/records/edit.html.erb
<%= content_for :body_id, "edit" %>
<section id="hero" class="container-fluid">
  <section class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1>Edit record #<%= @record.id %></h1>
      </div>
    </div>
  </section>
</section>
<section class="container-fluid">
  <section class="container">
    <div class="row">
      <div class="col-lg-8">
        <%= render "form", record: @record %>
        <br>
        <%= link_to "View", @record, class: "btn j-btn" %>
        <%= link_to "All records", records_path, class: "btn j-btn" %>
      </div>
    </div>
  </section>
</section>

app/views/records/index.html.erb
<%= content_for :body_id, "t-records" %>
<section class="container-fluid">
  <div class="container-lg">
    <div class="row">
      <div class="col-lg-12">
        <div class="success">
          <p><%= notice %></p>
        </div>
        <h1 class="heading">Thought records</h1>
        <p>All your records display here and are sorted by most recent first.</p>
        <%= link_to "New record", new_record_path, class: "btn j-btn new" %>
        <div id="records">
          <% @records.each do |record| %>
            <div class="col-lg-6 float-start">
              <div class="rec">
                <%= render record %>
                <%= link_to "View", record, class: "btn j-btn" %>
              </div>
            </div>
          <% end %>
          <section class="col-lg-12 float-start">
            <div class="paginator d-block float-end">
              <%= paginate @records %>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/records/new.html.erb
<%= content_for :body_id, "new" %>
<section class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1>New thought record</h1>
        <p>Starting a new thought record can be intimidating. Take your time, and ensure you're alone and won't be disturbed while you're completing it. All eight sections are required. If you feel that there is nothing to add to a section then enter "none".</p>
        <%= render "form", record: @record %>
        <section>
          <%= link_to "All records", records_path, class: "btn j-btn d-inline-block" %>
        </section>
      </div>
      <div class="col-lg-4">
        <div class="sticky">
<div class="container">
    <div class="row">
          <div class="col-lg-10 box">
            <h2>Sample questions for adaptive responses</h2>
            <p>Questions to help you compose alternative responses.</p>
            <ol>
              <li>What is the evidence that the automatic thought is true? Untrue?</li>
              <li>Is there an alternative explanation?</li>
              <li>If the worst happened, how could I cope? What's the best that could happen? What's the most realistic outcome?</li>
              <li>What's the effect of my believing the automatic thought? What could be the effect of my changing my thinking?</li>
              <li>If [person's name] was in this situation and had this thought, what would I tell them?</li>
              <li>What would be good to do?</li>
            </ol>
            <p>You can view the <%= link_to "12 types of cognitive distortions", faqs_path(anchor: "cognitive-distortions"), target: :_blank %> with examples on the 'FAQs' page.</p>
          </div>
        </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/records/show.html.erb
<%= content_for :body_id, "view" %>
<section class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1>Your thought record</h1>
      </div>
      <div class="rec col-lg-8">
        <div class="success">
          <p><%= notice %></p>
        </div>
        <%= render @record %>
      </div>
      <div class="col-lg-8">
        <%= link_to "Edit", edit_record_path(@record), class: "btn j-btn edit d-inline-block" %>
        <div class="d-inline-block">
          <%= button_to "Delete", @record, method: :delete, class: "btn j-btn delete" %>
        </div>
        <%= link_to "View records", records_path, class: "btn j-btn d-inline-block" %>
      </div>
    </div>
  </div>
</section>