config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :entries
  # get 'pages/home'
  root "pages#home"
  devise_for :users
  get "journal", to: "pages#journal"
  get "thoughts", to: "pages#thoughts"
  get "faqs", to: "pages#faqs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/faqs.html.erb
<%= content_for :body_id, "faqs" %>
<section id="hero" class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h1>Frequently asked questions</h1>
				<p class="col-lg-8">Find information on how to use journalite, psychotherapy, CBT, how to write a gratitude journal and more. journalite can help you craft your best possible journals and thought records for future keeping. Remember to be mindful and look after yourself. Your well-being is important, and we want you to your best possible self.</p>
			</div>
			<div class="col-lg-4 icon">
				<%= image_tag "happy-journalite-hero.png", width: "300px", height: "auto", class: "d-block" %>
			</div>
		</div>
	</div>
</section>
<section class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div id="how-to-use" class="col-lg-8">
				<h2>How to use <strong>journalite</strong></h2>
				<p>Getting started tends to be the difficult part of any journey. Journaling is no exception. Firstly, create an account by registering. Once you're account it set up, click "Journal" in the menu at the top and click on "New entry". Enter a date and time and then tick the box if it's a gratitude entry. The "Dear Journal" section is where you start typing your experiences, thoughts, feelings or actions for that day. How much detail you choose to write is your decision. Try to keep your journal informal regarding your use of language; however, if you feel more comfortable writing in a formal manner it's a good practice to be concise. Remember, it's your journal. It's private.</p>
			</div>
		</div>
	</div>
</section>
<section class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div id="cognitive-distortions" class="col-lg-8">
				<h2>Cognitive distortions</h2>
				<table>
					<thead>
						<tr>
							<th>Type of cognitive distortion</th>
							<th>Example</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>All-or-nothing thinking</td>
							<td>"If I'm not a total success, I'm a failure".</td>
						</tr>
						<tr>
							<td>Catastrophising (fortune telling)</td>
							<td>"I'll be so upset that I won't be able to function at all".</td>
						</tr>
						<tr>
							<td>Disqualifying or discounting the positive</td>
							<td>"I did that project well, but that doesn't mean I'm competent; I just got lucky".</td>
						</tr>
						<tr>
							<td>Emotional reasoning</td>
							<td>"I know I do a lot of things all right at work, but I still feel like I'm a failure".</td>
						</tr>
						<tr>
							<td>Labelling</td>
							<td>"I'm a loser". "He's bad".</td>
						</tr>
						<tr>
							<td>Magnification or minimisation</td>
							<td>"Getting a mediocre evaluation proves how inadequate I am". "Getting high marks doesn't mean I'm smart".</td>
						</tr>
						<tr>
							<td>Mental filter (selective abstraction)</td>
							<td>"I'm doing a lousy job because I received a low rating on my evaluation". Despite that it contained several high ratings.</td>
						</tr>
						<tr>
							<td>Mind reading</td>
							<td>"He's thinking that I don't know the first thing about this project".</td>
						</tr>
						<tr>
							<td>Overgeneralisation</td>
							<td>"I don't have what it takes to make friends because I felt uncomfortable at the social gathering".</td>
						</tr>
						<tr>
							<td>Personalisation</td>
							<td>"The repairman was curt to me because I did something wrong".</td>
						</tr>
						<tr>
							<td>'Should' and 'must' statements</td>
							<td>"It's terrible that I made a mistake. I should always do my best".</td>
						</tr>
						<tr>
							<td>Tunnel vision</td>
							<td>"My son's teacher cannot do anything right. He's critical and insensitive and lousy at teaching".</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<%= content_for :body_id, "home" %>
<section id="hero" class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h1>Discover the power of journaling with <span class="journalite"><em>journalite</em></span></h1>
				<%= button_to "Start journaling", new_entry_path, method: :get, class: "btn j-btn" %>
			</div>
		<div class="col-lg-4 icon">
			<%= image_tag "journalite-hero.png", width: "100%", height: "auto", class: "d-block" %>
		</div>
		</div>
	</div>
</section>
<section id="gratitude" class="container-fluid case">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h2>Keep a gratitude journal</h2>
				<p>Gratitude is the appreciation of what you considered as valuable and meaningful in your life; it is being thankful and appreciative for the things we have through experience or perception. Gratitude is an emotion we feel after someone helps us; it invokes a positive temperament when we notice the good in the World. When we feel or experience positivity, it can greatly affect our actions and impact our well-being for the better. Writing a gratitude journal is a proven way to increase your well-being and mindfulness.</p>
				<%= button_to "Create grateful memories", new_entry_path, method: :get, class: "btn j-btn" %>
			</div>
			<div class="col-lg-4 icon">
				<%= image_tag "thought-clouds.png", width: "auto", height: "auto", class: "d-block" %>
			</div>
		</div>
	</div>
</section>
<section id="cbt" class="container-fluid case">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h2>The power of <abbr title="Cognitive behavioural therapy.">CBT</abbr></h2>
				<p>CBT or cognitive behavioural therapy is a form of psychological treatment widely used in psychotherapy. Through talking and recording our thoughts, its methods helps us change the way we think and behave. Challenging our negative thoughts and subsequent actions is a key tenet of CBT. <strong>journalite</strong> can help you with the 'thought record' template developed by the Beck Institute. Create and view all your thought records knowing that they're secure and private.</p>
				<%= button_to "Create a thought record", new_record_path, method: :get, class: "btn j-btn" %>
			</div>
			<div class="col-lg-4 icon">
				<%= image_tag "gratitude-hero.png", width: "auto", height: "auto", class: "d-block" %>
			</div>
		</div>
	</div>
</section>
<section id="about" class="container-fluid case">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h2>About journalite</h2>
				<p>Love writing? Enjoy capturing your experiences, thoughts and feelings with journalite. Bring your notebook to life with a digital journal, or use the power of cognitive behavioural therapy (CBT) by creating a thought record. All your journal entries and thought records are safe and secure, and all in one place. <strong>journalite</strong> helps you question your negative thinking through the 'thought record' framework by the Beck Institute.</p>
				<p>The mind is a powerful phenomenon; our thoughts drive our perceptions, will, emotions and ultimately, govern how we behave. Discover more through journalite and bring the power of journaling into your life.</p>
			</div>
		</div>
	</div>
</section>
<section>
	<%= image_tag "happy-journalite.png", width: "auto", height: "auto", class: "happy-journalite" %>
</section>

app/views/pages/journal.html.erb
<%= content_for :title, @title %>
<%= content_for :body_id, "journal" %>
<section id="hero" class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h1 class="text-light">The power of the journal</h1>
				<h2 class="text-light">Writing how we feel is a powerful tool</h2>
				<p class="col-lg-8">Journaling is about keeping a record of your life. Document your experiences and feelings and be true to yourself. No one will judge you; your journal should be private and free from criticism. There is no requirement to create daily entries. We recommend writing two or three times a week, but the choice is yours.</p>
				<%= button_to "Create a journal entry", new_entry_path, method: :get, class: "btn j-btn" %>
			</div>
			<div class="col-lg-4 icon">
				<%= image_tag "journaling-hero.png", width: "100%", height: "auto", class: "d-block" %>
			</div>
		</div>
	</div>
</section>
<section id="j_entries" class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-12">
				<div id="entries">
					<h2 class="heading">Currently, you have no entries</h2>
					<p><span id="result"></span></p>
					<% if user_signed_in? %>
						<p><%= link_to "View entries", entries_path, class: "btn j-btn d-inline-block" %></p>
						<% @entries.each do |entry| %>
							<div class="col-lg-4 float-start">
								<div class="log">
									<%= render entry %>
									<%= link_to "View", entry, class: "btn j-btn" %>
								</div>
							</div>
						<% end %>
          			<% else %>
          				<span>Log in to create or view your journal entries.</span>
          			<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/pages/thoughts.html.erb
<%= content_for :body_id, "thoughts" %>
<section id="hero" class="container-fluid">
	<div class="container-lg">
		<div class="row">
			<div class="col-lg-8">
				<h1>Record your thoughts</h1>
				<h2>Remember to question negative thinking</h2>
				<p class="col-lg-8">Our thoughts govern how we feel and act. They can impact our lives in powerful ways and we tend to act on those impulses when emotions and tensions are high. Challenge your thinking; question the reasons why you feel a certain way at a certain moment. Start a thought record after you've experienced an unhelpful or unpleassant event or behaviour.</p>
				<%= button_to "Create a throught record", new_record_path, method: :get, class: "btn j-btn" %>
			</div>
			<div class="col-lg-4 icon">
				<%= image_tag "gratitude-hero.png", width: "auto", height: "auto", class: "d-block" %>
			</div>
		</div>
	</div>
</section>
<section id="t_records" class="container-fluid">
	<section class="container-lg">
		<div class="row">
			<div class="col-lg-12">
				<div id="records">
					<h2 class="heading">Currently, you have no records</h2>
					<p><span id="result"></span></p>
					<% if user_signed_in? %>
						<p><%= link_to "View records", records_path, class: "btn j-btn d-inline-block" %></p>
						<% @records.each do |record| %>
							<div class="col-lg-4 float-start">
								<div class="rec">
									<%= render record %>
									<%= link_to "View", record, class: "btn j-btn" %>
								</div>
							</div>
						<% end %>
					<% else %>
          				<span>Log in to create and view your thought records.</span>
          			<% end %>
				</div>
			</div>
		</div>
	</section>
</section>